### ISSUE TITLE
Drag action for copy and paste suddenly doesn't work.

### ISSUE THREAD

**Issue by DongHwanJang** [jacktrocinski/pretty-putty#1]
After applying modified .reg file, copy and paste using mouse action, which Putty supports, doesn't work.

**Comment by DongHwanJang** [comment]
> After applying modified .reg file, copy and paste using mouse action, which Putty supports, doesn't work.

I figureed it out. Config > Window > Selection > Action of Mouse buttons > Compromise. Don't know why this option have been changed.

**Comment by jacktrocinski** [comment]
Thanks :)

**Comment by DarthKoax** [comment]
Thanks, 
I came here to report this issue. Your solution fixed it.
