### ISSUE TITLE
Opening vi after connecting to server throws "putty-256colour: Unkown terminal type"

### ISSUE THREAD

**Issue by guruparan18** [jacktrocinski/pretty-putty#2]
After downloading the *.reg file and making the change for the session, I was able to connect to the remote server using Putty without any issue.

However, once in the remote server, when I try to open a log file in "vi", I get an error message as below and file is open in "ed".

"putty-256colour: Unkown terminal type"

![image](https://user-images.githubusercontent.com/242920/54830155-52d0e680-4c8e-11e9-9818-b731d822a811.png)

**Comment by jacktrocinski** [comment]
Hi,

I would highly recommend that you use Vim instead of Vi, however if that is
not an option then edit line 42 in the .reg file to:

"TerminalType"="xterm"

and then double click the .reg file to install the update.

Best,
Jack T.

**Comment by guruparan18** [comment]
Defining terminal type fixed the issue. Unfortunately, the box did not have Vim.
